### ISSUE TITLE
using lstm with cuda gives error

### ISSUE THREAD

**Issue by htoyryla** [spro/char-rnn.pytorch#2]
Command 
```
python train.py runoja.txt --n_epochs 5000 --model lstm --cuda
```

gives

```
Traceback (most recent call last):
  File "train_.py", line 95, in <module>
    loss = train(*random_training_set(args.chunk_len, args.batch_size))
  File "train_.py", line 55, in train
    hidden = hidden.cuda()
AttributeError: 'tuple' object has no attribute 'cuda'
```

Here https://github.com/spro/char-rnn.pytorch/blob/master/model.py#L38-L39 it looks like the hidden layers is indeed a tuple. Not sure about the correct way to make this work.

**Comment by berkersonmez** [comment]
Yes these changes seem to fix it.

**Comment by olivatooo** [comment]
See my fork, I'm trying to keep updated

https://github.com/olivatooo/char-rnn.pytorch
